version: '3.8'

services:
  web-statis:
    image: ${{ secrets.DOCKERHUB_USERNAME }}/himafor_2388010026:latest
    container_name: himafor-web-statis
    ports:
      - "80:80"
    restart: always
    networks:
      - himafor-network

networks:
  himafor-network:
    driver: bridge
